### ISSUE TITLE
Spike: Review USDS ReportStream Upload function

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-csv#18]
Report Stream - Server side
https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/ReportFunction.kt#L83

Simple Report - Client side

**Comment by mkrystof** [comment]
The USDS ReportStream upload functionality appears to use SFTP for transfers.  Given that, it doesn't seem necessary to get it running locally to evaluate further.  SFTP inherently doesn't support resumable uploads so there would need to be a redesign of the USDS ReportStream to migrate to an architecture that could support resumable uploads.
