### ISSUE TITLE
Test Tus resumability scenarios with azure portal deployment of tusd (single server instance)

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-csv#28]
Concern: Resumability scenarios 

Client
1. "Happy Path" - Manual pause and resume
2. Connectivity issue - disconnect client from internet for [30 s, 1 m, 5 m, 10 m]
5. Latency issue
     * ~Don't know how to execute this; try chrome dev-tools~
     * Using https://github.com/Shopify/toxiproxy

Server 
3. Pause tusd from Azure Portal
4. Daemon kill and restart (e.g., ctrl-d on server processes)
  * Mimic's tus daemon timeout

**Comment by mkrystof** [comment]
Client tests:
[ ] Manual disconnect, resumed 15 minutes later - SUCCESS
[ ] Manual disconnect several times with resume - SUCCESS

**Comment by mkrystof** [comment]
Install [toxiproxy](https://github.com/Shopify/toxiproxy)
```
$ brew tap shopify/shopify
$ brew install toxiproxy
```
In first terminal window:
```
$ toxiproxy-server
```

In second terminal window:
```
$ toxiproxy-cli create -l 127.0.0.1:26379 -u localhost:1080 tusd
$ toxiproxy-cli list
```
Note, with some work, you can also point to the server running in Azure.
```
$ toxiproxy-cli create -l localhost:26379 -u as-bulk-upload-tusd.azurewebsites.net:443 tusd
```

Run the tusd server locally via docker
```
docker run -p 1080:1080 --env AZURE_STORAGE_ACCOUNT=<insert account> --env AZURE_STORAGE_KEY=<insert key> tusproject/tusd -azure-blob-access-tier=hot -azure-object-prefix=tus-prefix -azure-storage=tus-file-container -azure-endpoint=https://<insert account>.blob.core.windows.net
```

In third terminal window:
```
$ tus-upload 10MB-test-file http://localhost:26379/files/
```

Upload to proxy
```
$ tus-upload flower.jpeg http://localhost:26379/files/
```

Bypass proxy upload
```
$ tus-upload flower.jpeg http://localhost:1080/files/
```

Add latency (milliseconds)
```
$ toxiproxy-cli toxic add -t latency -a latency=1000 tusd
$ toxiproxy-cli inspect tusd
```
Verify the latency shows as below:
```
Name: tusd	Listen: 127.0.0.1:26379	Upstream: localhost:1080
======================================================================
Upstream toxics:
Proxy has no Upstream toxics enabled.

Downstream toxics:
latency_downstream:	type=latency	stream=downstream	toxicity=1.00	attributes=[	jitter=0	latency=1000	]
```

Update downstream toxic to have 10 second latency
```
$ toxiproxy-cli toxic update -a latency=10000 -n latency_downstream tusd
```

Update downstream toxic to have 100 millsecond jitter
```
$ toxiproxy-cli toxic update -a jitter=100 -n latency_downstream tusd
```

Add upstream toxic
```
$ toxiproxy-cli toxic add --upstream -t latency -a latency=1000 tusd
$ toxiproxy-cli toxic update -a jitter=100 -n latency_upstream tusd
```

Add upstream toxic to limit bandwidth (kB/sec)
```
$ toxiproxy-cli toxic add --upstream -t bandwidth -a rate=100 tusd
```

Update upstream toxic to limit bandwidth (kB/sec)
```
$ toxiproxy-cli toxic update -a rate=1 -n bandwidth_upstream tusd
```
