### ISSUE TITLE
Create logical architecture diagram for NCIRD use case

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-csv#9]
Show
FROM POST by the submitter (IZ Gateway)
...
TO ADLS

Similar to "Lucid > Logical Component Diagram for HL7v2"

**Comment by rmharrison** [comment]
@sirishankar Please create the diagram in LucidChart alongside all the other DEX diagrams. :)

**Comment by sirishankar** [comment]
Tow Lucid charts were created - high level and api
